# -------------------------------------------------------------------------
#                                 AlthenosOS
#  (c) 2025-2026 littlefly365
#  This project is under the GPL v3 license.
#  You should receive the license with the source code. If not - check:
#  https://github.com/littlefly365/AlthenosOS/blob/main/LICENSE.md
# -------------------------------------------------------------------------

CC=clang
AS=clang -c
LD=ld.lld
CPP=clang++
CFLAGS =-Wno-error -w -fno-stack-protector -m32 -nostdlib -fno-builtin -fno-exceptions -ffreestanding -Wall -Wextra -Wpedantic
ASFLAGS =-m32
LDFLAGS =-melf_i386
VERSION=0.1.1
MAKEFLAGS= -j4

SRC_DIR=src
KERNEL_DIR=src/kernel
INCLUDE_DIR=include
BUILD_DIR=build
ISO_DIR=iso

BLUE    := \033[1;34m
GREEN   := \033[1;32m
YELLOW  := \033[1;33m
RED     := \033[1;31m
RESET   := \033[0m

ifeq ($(V),1)
Q :=
else
Q := @
endif

cmd_cc = printf "$(BLUE)  CC      $(RESET)%s\n" "$@"
cmd_as = printf "$(YELLOW)  AS      $(RESET)%s\n" "$@"
cmd_ld = printf "$(GREEN)  LD      $(RESET)%s\n" "$@"
cmd_cpp = printf "$(BLUE)  CPP     $(RESET)%s\n" "$@"

SRC_DRIVERS=$(wildcard $(KERNEL_DIR)/drivers/*.c)
SRC_SHELL=$(wildcard $(KERNEL_DIR)/ksh/*.c)
SRC_KERNEL=$(wildcard $(KERNEL_DIR)/arch/i386/*.c)
SRC_BIN=$(wildcard $(KERNEL_DIR)/bin/*.c)
SRC_BIN_CPP=$(wildcard $(KERNEL_DIR)/bin/*.cpp)
SRC_BOOT=$(wildcard $(KERNEL_DIR)/boot/*.S)
SRC_INITRD=$(BUILD_DIR)/initrd.tar

OBJ_DRIVERS=$(patsubst $(KERNEL_DIR)/drivers/%.c,$(BUILD_DIR)/drivers/%.o,$(SRC_DRIVERS))
OBJ_SHELL=$(patsubst $(KERNEL_DIR)/ksh/%.c,$(BUILD_DIR)/ksh/%.o,$(SRC_SHELL))
OBJ_KERNEL=$(patsubst $(KERNEL_DIR)/arch/i386/%.c,$(BUILD_DIR)/kernel/%.o,$(SRC_KERNEL))
OBJ_BIN=$(patsubst $(KERNEL_DIR)/bin/%.c,$(BUILD_DIR)/bin/%.o,$(SRC_BIN))
OBJ_BIN_CPP=$(patsubst $(KERNEL_DIR)/bin/%.cpp,$(BUILD_DIR)/bin/%.o,$(SRC_BIN_CPP))
OBJ_BOOT=$(patsubst $(KERNEL_DIR)/boot/%.S,$(BUILD_DIR)/boot/%.o,$(SRC_BOOT))
OBJ_INITRD=$(BUILD_DIR)/initrd.o

