# ============================================================
#               AlthenosOS - Makefile.config
# ============================================================

CC=clang
AS=as
CFLAGS = -Wno-error -w -fno-stack-protector -m32 -nostdlib -fno-builtin -fno-exceptions -ffreestanding -Wall -Wextra -Wpedantic
ASFLAGS = --32
LDFLAGS = -melf_i386
VERSION=0.1.0
MAKEFLAGS += -j$(nproc)

SRC_DIR=src
INCLUDE_DIR=include
BUILD_DIR=build
ISO_DIR=iso

# ------------------------------------------------------------
#   Colores estilo kernel Linux
# ------------------------------------------------------------
BLUE    := \033[1;34m
GREEN   := \033[1;32m
YELLOW  := \033[1;33m
RED     := \033[1;31m
RESET   := \033[0m

# ------------------------------------------------------------
#   Verbose Mode (make V=1)
# ------------------------------------------------------------
ifeq ($(V),1)
Q :=
else
Q := @
endif

# ------------------------------------------------------------
#   Pretty Print estilo Linux kernel
# ------------------------------------------------------------
cmd_cc = printf "$(BLUE)  CC      $(RESET)%s\n" "$@"
cmd_as = printf "$(YELLOW)  AS      $(RESET)%s\n" "$@"
cmd_ld = printf "$(GREEN)  LD      $(RESET)%s\n" "$@"
cmd_ar = printf "$(RED)  AR      $(RESET)%s\n" "$@"

# ------------------------------------------------------------
#   Archivos fuente
# ------------------------------------------------------------
SRC_DRIVERS=$(wildcard $(SRC_DIR)/drivers/*.c)
SRC_SHELL=$(wildcard $(SRC_DIR)/shell/*.c)
SRC_KERNEL=$(wildcard $(SRC_DIR)/kernel/i386/*.c)
SRC_BIN=$(wildcard $(SRC_DIR)/bin/*.c)
SRC_BOOT=$(wildcard $(SRC_DIR)/boot/*.s)
SRC_INITRD=$(BUILD_DIR)/initrd.tar

# Objetos
OBJ_DRIVERS=$(patsubst $(SRC_DIR)/drivers/%.c,$(BUILD_DIR)/drivers/%.o,$(SRC_DRIVERS))
OBJ_SHELL=$(patsubst $(SRC_DIR)/shell/%.c,$(BUILD_DIR)/shell/%.o,$(SRC_SHELL))
OBJ_KERNEL=$(patsubst $(SRC_DIR)/kernel/i386/%.c,$(BUILD_DIR)/kernel/%.o,$(SRC_KERNEL))
OBJ_BIN=$(patsubst $(SRC_DIR)/bin/%.c,$(BUILD_DIR)/bin/%.o,$(SRC_BIN))
OBJ_BOOT=$(patsubst $(SRC_DIR)/boot/%.s,$(BUILD_DIR)/boot/%.o,$(SRC_BOOT))
OBJ_INITRD=$(BUILD_DIR)/initrd.o

